# This is a basic workflow to help you get started with Actions

name: Merge Pull Request and create custom builds

# Controls when the workflow will run
on:
  # pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0/45 * * * *' 

# Environment Variables
env:
  auth: ${{ secrets.auth }}
  USER_NAME: ${{ secrets.USER_NAME }}
  EMAIL: ${{ secrets.EMAIL }}
  DISPLAY_RESPONSE: ${{ secrets.DISPLAY_RESPONSE }}
  REPO: ${{ github.event.repository.name }}
  OWNER: ${{ github.event.repository.owner.login }}
  SF_PWD: ${{ secrets.SF_PWD }}
  RELEASE_TYPE: 'stable'
  ENVIRONMENT_TYPE: ${{ secrets.ENVIRONMENT_TYPE }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    # if: github.event.repository.owner.login == 'nikgapps' 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup SSH Keys and known_hosts 
        uses: webfactory/ssh-agent@v0.4.1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            
      - name: Environment Details and clean up
        run: |
          rm -rf Build 10 11 12 Releases canary-release release nikgapps.github.io TempPackages
          echo "repo: $REPO"
          echo "repo owner: $OWNER"
          
      - name: Initialization and Fetching the Source Code
        run: |
           git config --global user.name "$USER_NAME"
           git config --global user.email "$EMAIL"
           git config --global http.postBuffer 1048576000
           git clone --depth=1 git@github.com:nikhilmenghani/build.git
           
      - name: Installing Requirements
        run: |
           python3 -m pip install wheel setuptools testresources
           cd build
           pip3 install -r requirements.txt
           cd ..
      
      - name: Merging Pull Requests
        run: |
           cd build
           python3 git_control.py
           cd ..
      - name: Get the configs to build
        run: |
           git clone --depth=1 git@github.com:nikgapps/config.git
                       
      - name: Building Custom Builds for android 10
        run: |
           cd build
           python3 config_control.py 10
           cd ..
     
      - name: Building Custom Builds for android 11
        run: |
           cd build
           python3 config_control.py 11
           cd ..
           
      - name: Building Custom Builds for android 12
        run: |
           cd build
           python3 config_control.py 12
           cd ..
      
      - name: Building Custom Builds for android 12L
        run: |
           cd build
           python3 config_control.py 12.1
           cd ..
           
      - name: Updating download count
        run: |
           cd build
           python3 analytics_control.py
           cd ..
