name: Matrix Test

on:
  workflow_dispatch:

jobs:
  matrix:
    name: Generate build matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup.outputs.matrix }}
    steps:

      - name: Generate build matrix
        id: setup
        uses: actions/github-script@v6
        with:
          script: |
            let matrix = {};
            matrix.androidv = ["10", "11", "12", "12.1", "13"]
            matrix.arch = ["arm", "arm64", "x86", "x86_64"]
            core.setOutput("matrix", JSON.stringify(matrix));

  build:
    name: Build ${{ matrix.androidv }}-${{ matrix.arch }}
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:

      - name: Map Android Version to tree
        run: |
          echo matrix.androidv
          echo matrix.arch

      - name: Clone repository
        run: |
          echo "hi"
